version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/Database.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend_net

  api:
    build: ./api
    container_name: backend_api
    ports:
      - "8000:8000"
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - backend_net
    restart: unless-stopped

volumes:
  mysql_data:

networks:
  backend_net: